resources:
  - name: gosvc_gitRepo_t
    type: GitRepo
    configuration:
      path: tarunaz/go-service
      gitProvider: tarunm_github

  - name: gosvc_build_info_t
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory
      buildName: svc_build
      buildNumber: 1

  - name: gosvc_promoted_build_info_t
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory
      buildName: svc_build
      buildNumber: 1

  - name: be_gitRepo_t
    type: GitRepo
    configuration:
      path: tarunaz/java-backend
      gitProvider: tarunm_github

  - name: appl_build_info_output_t
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory
      buildName: backend_build
      buildNumber: 1

  - name: appl_build_info_t
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory
      buildName: backend_build
      buildNumber: 1

  - name: appl_promoted_build_info_t
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory
      buildName: backend_build
      buildNumber: 1

  - name: fe_gitRepo_t
    type: GitRepo
    configuration:
      path: tarunaz/vue-frontend
      gitProvider: tarunm_github

  - name: release_bundle_t
    type: ReleaseBundle
    configuration:
      sourceDistribution: Distribution
      name: demo_rb
      version: v1.0.0

  - name: signed_bundle_t
    type: ReleaseBundle
    configuration:
      sourceDistribution: Distribution
      name: demo_rb
      version: v1.0.0

  - name: distribution_rules_t
    type: DistributionRule
    configuration:
      sourceDistribution: Distribution
      serviceName: "*"
      siteName: "*"
      cityName: "*"
      countryCodes:
        - "CN"
        - "GB"

pipelines:
  - name: demo_gosvc_t
    steps:
      - name: bld_svc
        type: DockerBuild
        configuration:
          affinityGroup: bldGroup
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: tarunm-docker-dev-local.artifactory-unified.soleng-us.jfrog.team/gosvc
          dockerImageTag: ${run_number}
          inputResources:
            - name: gosvc_gitRepo_t
          integrations:
            - name: Artifactory

      - name: push_svc
        type: DockerPush
        configuration:
          affinityGroup: bldGroup
          targetRepository: tarunm-docker-dev-local
          forceXrayScan: false
          failOnScan: false
          autoPublishBuildInfo: true
          integrations:
            - name: Artifactory
          inputSteps:
            - name: bld_svc
          outputResources:
            - name: gosvc_build_info_t

      - name: promote_svc_build
        type: PromoteBuild
        configuration:
          targetRepository: tarunm-docker-qa-local
          integrations:
            - name: Artifactory
          inputResources:
            - name: gosvc_build_info_t
          outputResources:
            - name: gosvc_promoted_build_info_t

  - name: demo_application_t
    steps:
      - name: bld_backend
        type: MvnBuild
        configuration:
          sourceLocation: .
          mvnCommand: clean install -ntp
          configFileLocation: .
          configFileName: mvn-art-config
          inputResources:
            - name: be_gitRepo_t
          integrations:
            - name: Artifactory
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "11"
        execution:
          onStart:
            - javac -version
            - mvn --version

      - name: bld_frontend
        type: NpmBuild
        configuration:
          npmArgs: --no-progress --no-audit
          sourceLocation: .
          repositoryName: npm-virtual
          inputResources:
            - name: fe_gitRepo_t
          integrations:
            - name: Artifactory

      - name: pack_frontend
        type: Bash
        configuration:
          inputSteps:
            - name: bld_frontend
          integrations:
            - name: Artifactory
        execution:
          onStart:
            - export tempStateLocation="$step_tmp_dir/npmSourceState"
            - restore_run_files npmBuildInputGitRepo $tempStateLocation
            - pushd $tempStateLocation
            - npm run build
            - add_run_files $tempStateLocation/. npmBuildInputGitRepo

      - name: publish_frontend
        type: NpmPublish
        configuration:
          repositoryName: npm-local
          inputSteps:
            - name: pack_frontend
          integrations:
            - name: Artifactory
        execution:
          onStart:
            - export inputNpmBuildStepName="bld_frontend"

      - name: build_app
        type: Bash
        configuration:
          environmentVariables:
            dockerImageName: tarunm-docker-dev-local.artifactory-unified.soleng-us.jfrog.team/app
            dockerImageTag: ${run_number}
          inputResources:
            - name: be_gitRepo_t
              trigger: false
          inputSteps:
            - name: bld_backend
            - name: publish_frontend
          integrations:
            - name: Artifactory
        execution:
          onStart:
            - rm -rf $run_dir/workspace/jfrog
            - retry_command jfrog rt config --url $int_demo_art_url --user $int_demo_art_user --apikey $int_demo_art_apikey --interactive=false
            - pushd $res_be_gitRepo_resourcePath
            - add_run_variables buildStepName=${step_name}
            - add_run_variables ${step_name}_buildNumber=${run_number}
            - add_run_variables ${step_name}_buildName=${pipeline_name}
            - docker build --pull --no-cache -t $dockerImageName:$dockerImageTag --build-arg REGISTRY=${int_demo_art_url} .
            - jfrog rt bce $pipeline_name $run_number
            - jfrog rt docker-push $dockerImageName:$dockerImageTag docker-local --build-name=$pipeline_name --build-number=$run_number
            - add_run_files /tmp/jfrog/. jfrog

      - name: publish_app_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: build_app
          outputResources:
            - name: appl_build_info_t

      - name: promote_app_build
        type: PromoteBuild
        configuration:
          targetRepository: tarunm-docker-qa-local
          integrations:
            - name: Artifactory
          inputResources:
            - name: appl_build_info_t
          outputResources:
            - name: appl_promoted_build_info_t

  - name: demo_release_mgmt_t
    steps:
      - name: bundle
        type: CreateReleaseBundle
        configuration:
          releaseBundleName: demo_rb
          releaseBundleVersion: v1.0.${run_number}
          dryRun: false
          sign: false
          description: "some random test description"
          inputResources:
            - name: gosvc_promoted_build_info_t
              trigger: false
            - name: appl_promoted_build_info_t
              trigger: false
          outputResources:
            - name: release_bundle_t
          releaseNotes:
            syntax: markdown
            content: |
              ## Heading
                * Bullet
                * Points

      - name: sign
        type: SignReleaseBundle
        configuration:
          inputResources:
            - name: release_bundle_t
          outputResources:
            - name: signed_bundle_t

      - name: distribute
        type: DistributeReleaseBundle
        configuration:
          dryRun: false
          inputResources:
            - name: signed_bundle_t
            - name: distribution_rules_t
